### ISSUE TITLE
plugin crashes on use

### ISSUE THREAD

**Issue by NobbZ** [idris-hackers/atom-language-idris#120]
Try to edit some idris file and use any of the features that the package should provide.

Situations I am able to reproduce easily:
- Have autocompletion pop up
- Typecheck (CTRL-ALT-R)
- do anything with a hole
- add a clause

**Atom Version**: 1.8.0
**Idris Version**: 0.11.2 (via stack, lts-6.2)
**System**: Windows 10 64bit
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.4.5
### Stack Trace

Uncaught At 0 expected: ( found: f

```
At C:\Users\xxx\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:756

At undefined undefined
    at Object.<anonymous> (C:\Users\xxx\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:141:25)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\xxx\.atom\packages\language-idris\node_modules\bennu\index.js:2:14)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/language-idris/lib/parse.coffee:1:25)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/language-idris/lib/parse.coffee:1:1)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at Object.<anonymous> (file:///C:/Users/xxx/.atom/packages/language-idris/lib/idris-ide-mode.coffee:1:1)
    at Module._compile (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\xxx\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
```
### Commands

```
     -1:00.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:copy (atom-text-editor.editor.autocomplete-active.is-focused)
  2x -0:13.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:11.3.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -0:09.8.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "language-idris": {
    "panelFontLigatures": true,
    "pathToIdris": "c:\\Users\\xxx\\AppData\\Roaming\\local\\bin\\idris.exe"
  }
}
```
### Installed Packages

``` coffee
# User
language-idris, v0.4.5

# Dev
No dev packages
```

**Comment by NobbZ** [comment]
I can't reproduce this with newer versions of everything, independent of the OS used. So I will close this report.
