### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by wolverian** [idris-hackers/atom-language-idris#121]
1. Enter code that doesn't compile
2. Press ctrl-alt-r to load the file
3. Wait for the error pane to show the compilation error
4. Click the error location. This pops up the error.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.12
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.4.5
### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/iv/.atom/packages/language-idris/node_modules/atom-message-panel/lib/LineMessageView.js:52

TypeError: Cannot read property 'getPath' of undefined
    at [object Object].LineMessageView.goToLine (/Users/iv/.atom/packages/language-idris/node_modules/atom-message-panel/lib/LineMessageView.js:52:53)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -1:01.8.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:01.8.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:01.0 core:undo (atom-text-editor.editor.is-focused)
     -1:00.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:59.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.7.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:59 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:58.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:48.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:48.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.9.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.5.0 core:confirm (atom-pane.pane.active)
     -0:11.4.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -0:09.3.0 core:confirm (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "vim-mode",
      "vim-surround"
    ],
    "themes": [
      "one-dark-ui",
      "firewatch-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
firewatch-syntax, v1.0.1
gist-it, v0.9.1
haskell-pointfree, v0.1.3
language-haskell, v1.7.17
language-idris, v0.4.5
language-purescript, v0.7.0

# Dev
No dev packages
```

**Comment by justjoheinz** [comment]
Issue maintanenance - cannot reproduce.  Please reopen if the issue still exists with the latest released package.
