### ISSUE TITLE
This 6-character program (bad_comment.idr) crashes Idris for atom

### ISSUE THREAD

**Issue by kevinsullivan** [idris-hackers/atom-language-idris#128]
==== Program ====

{-
{-
-}

==== Stack trace ====

TypeError: Cannot read property 'length' of undefined
    at IdrisController.displayErrors (/Users/sullivan/.atom/packages/language-idris/lib/idris-controller.coffee:418:5)
    at AnonymousObserver._onError (/Users/sullivan/.atom/packages/language-idris/lib/idris-controller.coffee:1:1)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1643:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at AnonymousObserver.tryCatcher (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.error (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:4667:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1872:48)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at loopRecursive (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2412:18)
    at invokeRecImmediate [as action](/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:929:7)
    at ScheduledItem.invokeCore (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at ScheduledItem.invoke (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at FilterObservable.Rx.ObservableBase.ObservableBase._subscribe (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/sullivan/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)

**Comment by melted** [comment]
Thanks for the report!

**Comment by justjoheinz** [comment]
idris itself chokes on this snippet. Atom is notified that the process terminated, but in the aftermath of it, it fails to recreate the REPL process, printing an error message that the socket has been ended by the other party.

**Comment by justjoheinz** [comment]
Related: https://github.com/idris-lang/Idris-dev/issues/4013

**Comment by justjoheinz** [comment]
```
  |
4 | 
  | ^
unexpected end of input
expecting end of comment
```

Idris now reponds with a fairly reasonable message.
