### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getURI' of undefined

### ISSUE THREAD

**Issue by PhilAndrew** [idris-hackers/atom-language-idris#147]
C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:78
Hide Stack Trace
TypeError: Cannot read property 'getURI' of undefined
    at IdrisController.openREPL (file:///C:/Users/philip/.atom/packages/language-idris/lib/idris-controller.coffee:378:17)
    at file:///C:/Users/philip/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
    at AnonymousObserver._onNext (file:///C:/Users/philip/.atom/packages/language-idris/lib/idris-controller.coffee:65:11)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1635:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1569:31)
    at AnonymousObserver.tryCatcher (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1569:31)
    at CatchObserver.next (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2747:59)
    at CatchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1569:31)
    at CatchObserver.tryCatcher (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1569:31)
    at InnerObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3263:90)
    at InnerObserver.tryCatcher (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1569:31)
    at scheduleItem (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2651:16)
    at JustSink.run (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2659:9)
    at JustObservable.subscribeCore (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2640:19)
    at JustObservable.tryCatcher (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
    at setDisposable [as action] (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1813:46)
    at ScheduledItem.invokeCore (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:858:33)
    at ScheduledItem.invoke (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:846:40)
    at runTrampoline (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1045:37)
    at tryCatcher (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1061:45)
    at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1826:32)
    at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1703:19)
    at MergeAllObserver.onNext (C:\Users\philip\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3232:37)

**Comment by melted** [comment]
Thanks for the bug report! That's a really weird crash.

**Comment by PhilAndrew** [comment]
On Windows, Atom 1.13.0 ia32. Sad, because I cannot use it.

**Comment by adrood** [comment]
Similar errors on MacOS.

**Comment by melted** [comment]
Looks like there's a change in Atom 1.13.0.

**Comment by Synthetica9** [comment]
Same on Arch, atom 1.13.0.

**Comment by melted** [comment]
Yeah, I see what the problem is. What element is sent to commands has been changed. I'm working on a fix.

**Comment by archaeron** [comment]
too bad it's all in coffeescript. TypeScript would probably have caught that :(

this should work:
change this:
https://github.com/idris-hackers/atom-language-idris/blob/master/lib/idris-controller.coffee#L115
to:
typecheckFile: (args) =>
    uri = args.currentTarget.editor.getURI()

**Comment by melted** [comment]
One can get the active editor from atom.workspace, so I did that.

**Comment by melted** [comment]
I have published 0.4.7, I'll write some release notes after dinner.

**Comment by goofballLogic** [comment]
how was dinner?
