### ISSUE TITLE
Crashes with v0.4.9

### ISSUE THREAD

**Issue by machunter** [idris-hackers/atom-language-idris#167]
I've just upgraded to v0.4.9 and started seeing crashes. I rolled back to 0.4.8 and it seems to have cleared it up.

`
**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/burc/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:78

TypeError: Cannot read property 'length' of undefined
    at IdrisController.displayErrors (/packages/language-idris/lib/idris-controller.coffee:434:39)
    at AnonymousObserver._onError (/packages/language-idris/lib/idris-controller.coffee:1:1)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1643:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at AnonymousObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4667:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1872:48)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at loopRecursive (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2412:18)
    at /packages/language-idris/node_modules/rx-lite/rx.lite.js:929:7)
    at ScheduledItem.invokeCore (/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at ScheduledItem.invoke (/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at FilterObservable.Rx.ObservableBase.ObservableBase._subscribe (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)
```

### Commands

```
  3x -1:05.7.0 core:backspace (input.hidden-input)
     -0:53.6.0 editor:newline (input.hidden-input)
     -0:53.2.0 snippets:next-tab-stop (input.hidden-input)
     -0:53.2.0 snippets:expand (input.hidden-input)
     -0:53.2.0 editor:indent (input.hidden-input)
  2x -0:52 core:backspace (input.hidden-input)
     -0:50 editor:newline (input.hidden-input)
     -0:49.7.0 snippets:next-tab-stop (input.hidden-input)
     -0:49.7.0 snippets:expand (input.hidden-input)
     -0:49.7.0 editor:indent (input.hidden-input)
 10x -0:43.1.0 core:backspace (input.hidden-input)
     -0:33.9.0 editor:newline (input.hidden-input)
     -0:17.2.0 core:save (input.hidden-input)
     -0:09.9.0 core:move-left (input.hidden-input)
     -0:08.7.0 core:save (input.hidden-input)
     -0:07.8.0 language-idris:typecheck (input.hidden-input)
```

### Non-Core Packages

```
git-plus 7.4.0 
highlight-selected 0.13.1 
irc 0.4.0 
language-idris 0.4.9 
pretty-json 1.6.3 
```

`

**Comment by machunter** [comment]
Actually it looks like my Idris compiler is crashing (unclear why), and this is the aftermath. Still happening with v0.4.8.

**Comment by melted** [comment]
I would make sense to present an idris failure in a nicer way though than a crash.

**Comment by justjoheinz** [comment]
@machunter Can you provide a small gist with a reproducible case?

**Comment by justjoheinz** [comment]
related #128 - but this has a better error message already and doe not run into .length undefined.

**Comment by atacratic** [comment]
(my guess is this is a dup of #106)
