### ISSUE TITLE
Nothing happens after requesting a type check

### ISSUE THREAD

**Issue by atacratic** [idris-hackers/atom-language-idris#172]
I've loaded the contrib.ipkg file from the Idris-dev repo, and am editing libs/contrib/Interfaces/Verified.idr.  I hit ctrl-alt-r to typecheck a file, but nothing happens.

Repro steps:
- check out commit 228784 of https://github.com/atacratic/Idris-dev/tree/VerifiedImpls_
- in atom do 'open folder' on libs/contrib
- open Verified.idr
- ctrl-alt-r
- nothing happens
- (I see in task manager that atom has started an idris process - it's using about 5 MB memory but no CPU).

Likewise if I do Packages > Idris > Typecheck, or Open REPL.

Atom diags (triggered when I did 'Stop Compiler' and then later hit the crash in #106, so probably not helpful):

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Chris\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:78

TypeError: Cannot read property 'length' of undefined
    at IdrisController.displayErrors (/packages/language-idris/lib/idris-controller.coffee:434:39)
    at AnonymousObserver._onError (/packages/language-idris/lib/idris-controller.coffee:1:1)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1643:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at AnonymousObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1879:58)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4667:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1872:48)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at loopRecursive (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2412:18)
    at /packages/language-idris/node_modules/rx-lite/rx.lite.js:929:7)
    at ScheduledItem.invokeCore (/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at ScheduledItem.invoke (/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at MergeAllObservable.Rx.ObservableBase.ObservableBase._subscribe (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at MergeAllObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)
    at IdrisController.getTypeForWord (/packages/language-idris/lib/idris-controller.coffee:179:8)
    at /packages/language-idris/lib/idris-controller.coffee:1:1
    at AnonymousObserver._onNext (/packages/language-idris/lib/idris-controller.coffee:80:11)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1635:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at AnonymousObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2747:59)
    at CatchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3263:90)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4329:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at AsyncSubject.onCompleted (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6462:17)
    at handler (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4766:7)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

### Commands

```
     -0:19.4.0 language-idris:stop-compiler (input.hidden-input)
     -0:17.1.0 language-idris:type-of (input.hidden-input)
```

### Non-Core Packages

```
haskell-hoogle 0.1.2 
language-haskell 1.4.4 
language-idris 0.4.9 
```

**Comment by justjoheinz** [comment]
Sorry for the late reply. In general it is pretty difficult to edit idris with atom. The least you need to do, is compile your version of idris beforehand and set the compiler in atom to use that version, but I have not tried that yet.

**Comment by atacratic** [comment]
I assume you mean 'difficult to edit the idris implementation and libraries' rather than 'difficult to edit code that's in idris'.  

Will close!
