### ISSUE TITLE
Uncaught At 0 expected: ( found: 5

### ISSUE THREAD

**Issue by marklemay** [idris-hackers/atom-language-idris#174]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.9

### Stack Trace

Uncaught At 0 expected: ( found: 5

```
At C:\Users\Mark\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:756

At undefined undefined
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:141:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/node_modules/bennu/index.js:2:14)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/parse.coffee:1:25)
    at /packages/language-idris/lib/parse.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
```

### Commands

```
     -3:45.2.0 language-idris:proof-search (input.hidden-input)
     -3:25.8.0 core:copy (input.hidden-input)
     -3:24.7.0 core:paste (input.hidden-input)
  3x -3:17.6.0 core:backspace (input.hidden-input)
     -3:11.8.0 core:copy (input.hidden-input)
     -3:11 core:paste (input.hidden-input)
     -3:08.2.0 language-idris:typecheck (input.hidden-input)
     -3:05.4.0 core:copy (input.hidden-input)
     -2:42.3.0 core:backspace (input.hidden-input)
     -2:32.6.0 core:copy (input.hidden-input)
     -2:31.9.0 core:paste (input.hidden-input)
     -2:31.4.0 core:save (input.hidden-input)
     -2:26.1.0 language-idris:typecheck (input.hidden-input)
  3x -2:20.1.0 core:save (input.hidden-input)
     -2:07.6.0 language-idris:typecheck (input.hidden-input)
     -2:01.3.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
language-idris 0.4.9 
```

**Comment by melted** [comment]
It's probably time to cut a new release if we can fix this.
