### ISSUE TITLE
Uncaught At 0 expected: ( found: l

### ISSUE THREAD

**Issue by jheiling** [idris-hackers/atom-language-idris#179]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.9

### Stack Trace

Uncaught At 0 expected: ( found: l

```
At C:\Users\Admin\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:756

At undefined undefined
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:141:25)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/node_modules/bennu/index.js:2:14)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/parse.coffee:1:25)
    at /packages/language-idris/lib/parse.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
```

### Commands

```
     -0:20.2.0 language-idris:open-repl (input.hidden-input)
```

### Non-Core Packages

```
ionide-fake 1.2.2 
ionide-fsharp 1.9.3 
ionide-fsi 2.1.3 
ionide-installer 1.4.0 
ionide-webview 1.0.3 
ionide-yeoman 2.0.0 
language-elm 1.5.0 
language-idris 0.4.9 
```

**Comment by justjoheinz** [comment]
Do you happen to have an ipkg file in the project directory. If so - what are the contents? Could you paste it here please?

**Comment by jheiling** [comment]
I found out what's going on... I had a file named IO.idr in the folder. Idris doesn't like that at all :(

**Comment by justjoheinz** [comment]
Did the file have any particular content? I still think the error is
strange.


2017-08-04 11:23 GMT+02:00 Jürgen Heiling <notifications@github.com>:

**Comment by justjoheinz** [comment]
This issue is a duplicate of issue #174

**Comment by mrakgr** [comment]
@jheiling Thanks for the heads up. Putting `IO.idr` in the project directory also broke everything for me too, not just for Atom, but for the VS Code plugin as well.
