### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by ehleezah** [idris-hackers/atom-language-idris#189]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.10

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\User\.atom\packages\language-idris\lib\utils\ipkg.coffee:12

TypeError: Cannot read property 'path' of undefined
    at findIpkgFile (/packages/language-idris/lib/utils/ipkg.coffee:12:42)
    at Object.compilerOptions (/packages/language-idris/lib/utils/ipkg.coffee:59:23)
    at Object.getSuggestions (/packages/language-idris/lib/idris-controller.coffee:117:14)
    at ~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:337:60
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:313:23)
    at AutocompleteManager.findSuggestions (~/AppData/Local/atom/app-1.20.0/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:302:25)
```

### Commands

```
     -9:09.4.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -9:06.1.0 core:confirm (input.hidden-input)
     -8:48.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
language-idris 0.4.10 
```

**Comment by andorp** [comment]
It also occurs after an installation and restart of atom
Debian 8.6
Idris 1.3
Atom: 1.9.2

**Comment by jeffwardnku** [comment]
I have the same issue.  Uninstalling the plugin, and also uninstalling Atom, didn't help.

**Comment by nicschumann** [comment]
This might be belated, but I've found that a key difference for me is whether I explicitly open a file (`atom foo.idr`) or a project directory (`atom foo-project`). In the former case, I get this exception. In the latter case, all seems to work fine. Maybe a debugging clue for you package implementers.

**Comment by bgavran** [comment]
I also started having this issue - I've had Atom open for a while (and used the idris plugin) and then restarted it, after which this issue appeared and now the plugin seems to be stuck in this unusable mode.

**Comment by allenjhan** [comment]
I get this exception when I try to start the REPL. I first created a file called test.idr. It doesn't matter whether I open test.idr or open the folder that contains it. Since I am on a Mac, the key bindings for the REPL are control+command+enter. As soon as I try to start the REPL, I get this exception.

Here is the stacktrace:
```
TypeError: Cannot read property 'setEncoding' of undefined
    at IdrisIdeMode.start (/Users/allen/.atom/packages/language-idris/lib/idris-ide-mode.coffee:48:23)
    at IdrisModel.ideMode (/Users/allen/.atom/packages/language-idris/lib/idris-model.coffee:23:19)
    at IdrisModel.prepareCommand (/Users/allen/.atom/packages/language-idris/lib/idris-model.coffee:89:6)
    at IdrisModel.interpret (/Users/allen/.atom/packages/language-idris/lib/idris-model.coffee:132:6)
    at IdrisModel.changeDirectory (/Users/allen/.atom/packages/language-idris/lib/idris-model.coffee:93:6)
    at IdrisModel.load (/Users/allen/.atom/packages/language-idris/lib/idris-model.coffee:105:10)
    at IdrisController.openREPL (/Users/allen/.atom/packages/language-idris/lib/idris-controller.coffee:546:8)
    at /Users/allen/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
    at AnonymousObserver._onNext (/Users/allen/.atom/packages/language-idris/lib/idris-controller.coffee:115:11)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1635:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at AnonymousObserver.tryCatcher (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.next (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2747:59)
    at CatchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.tryCatcher (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3263:90)
    at InnerObserver.tryCatcher (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at scheduleItem (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2651:16)
    at JustSink.run (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2659:9)
    at JustObservable.subscribeCore (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2640:19)
    at JustObservable.tryCatcher (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at Rx.internals.ScheduledItem.setDisposable [as action] (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1813:46)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/Users/allen/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
```

This is the first time I've ever used Atom. The only other package I installed was vim-mode-plus.
