### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by stocks29** [idris-hackers/atom-language-idris#19]
[Enter steps to reproduce below:]

1. installed language-idris plugin

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [language-idris](https://github.com/fangel/atom-language-idris) package, v0.1.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/bob/.atom/packages/language-idris/lib/idris-controller.coffee:29

TypeError: undefined is not a function
  at new IdrisController (/Users/bob/.atom/packages/language-idris/lib/idris-controller.coffee:29:21)
  at Socket.module.exports.startIdrisProcesses (/Users/bob/.atom/packages/language-idris/lib/language-idris.coffee:35:11)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -0:35.8.0 command-palette:toggle (atom-pane.pane.active)
  5x -0:33.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:31.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.6.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
  2x -0:24.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.2.6
haskell-ghc-mod, v0.6.3
ide-haskell, v0.5.7
iex, v0.9.9
language-elixir, v0.5.0
language-haskell, v1.0.0
language-idris, v0.1.1
linter, v0.12.6
linter-elixirc, v0.2.2
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by archaeron** [comment]
hello
thank you for reporting this bug.

this is interesting. the function `atom.workspace.getActivePaneItem()` here:
https://github.com/idris-hackers/atom-language-idris/blob/v0.1.1/lib/idris-controller.coffee#L28

returns a different object on Windows than it does on Mac.
I'll try to fix the bug today or tomorrow.
