### ISSUE TITLE
Exception when trying to get a type of hole

### ISSUE THREAD

**Issue by SamuraiJack** [idris-hackers/atom-language-idris#190]
[Enter steps to reproduce:]

1. 
```idris
module Baby

palindrome : String -> Bool

palindrome str = ?asd
```
2. Press ctrl+t on the "?asd" hole.

Does atom depends on the system-level node? I have node 6.2.0. Is there a recommended minimal node version for "language-idris" to work?

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Ubuntu 14.04.5
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.10

### Stack Trace

Uncaught TypeError: Cannot read property 'removeAllListeners' of null

```
At /home/nickolay/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:78

TypeError: Cannot read property 'removeAllListeners' of null
    at IdrisModel.ideMode (/packages/language-idris/lib/idris-model.coffee:17:26)
    at IdrisModel.prepareCommand (/packages/language-idris/lib/idris-model.coffee:89:6)
    at IdrisModel.interpret (/packages/language-idris/lib/idris-model.coffee:132:6)
    at IdrisModel.changeDirectory (/packages/language-idris/lib/idris-model.coffee:93:6)
    at IdrisModel.load (/packages/language-idris/lib/idris-model.coffee:105:10)
    at IdrisController.getTypeForWord (/packages/language-idris/lib/idris-controller.coffee:200:8)
    at /packages/language-idris/lib/idris-controller.coffee:1:1
    at AnonymousObserver._onNext (/packages/language-idris/lib/idris-controller.coffee:102:11)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1635:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at AnonymousObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2747:59)
    at CatchObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at CatchObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3263:90)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at scheduleItem (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2651:16)
    at JustSink.run (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2659:9)
    at JustObservable.subscribeCore (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2640:19)
    at JustObservable.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at /packages/language-idris/node_modules/rx-lite/rx.lite.js:1813:46)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)
    at MergeAllObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3232:37)
    at MergeAllObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1876:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4329:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at AsyncSubject.onCompleted (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6462:17)
    at handler (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4766:7)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -7:19.2.0 application:open-folder (div.tool-panel.tree-view)
     -6:48.5.0 language-idris:typecheck (div.lines)
     -5:15.3.0 language-idris:type-of (span.syntax--source.syntax--idris)
     -5:02.1.0 core:save (input.hidden-input)
     -4:59.1.0 language-idris:typecheck (div.line)
     -3:46.8.0 core:move-up (input.hidden-input)
  4x -3:46.3.0 editor:move-to-end-of-word (input.hidden-input)
     -3:45 editor:move-to-beginning-of-word (input.hidden-input)
     -3:42.1.0 editor:select-to-end-of-line (input.hidden-input)
     -3:39.7.0 core:save (input.hidden-input)
     -3:27.8.0 symbols-view:go-to-declaration (span.syntax--source.syntax--idris)
     -3:22.7.0 tree-view:show-current-file-in-file-manager (span.syntax--source.syntax--idris)
     -3:16.6.0 symbols-view:go-to-declaration (span.syntax--source.syntax--idris)
     -2:40.5.0 language-idris:holes (input.hidden-input)
     -1:58.6.0 core:move-left (input.hidden-input)
     -1:49.7.0 language-idris:type-of (input.hidden-input)
```

### Non-Core Packages

```
language-idris 0.4.10 
```

**Comment by SamuraiJack** [comment]
Turned out to be just an absence of absolute path to "idris" binary.
