### ISSUE TITLE
Uncaught At 0 expected: ( found: f

### ISSUE THREAD

**Issue by sjmackenzie** [idris-hackers/atom-language-idris#193]
[Enter steps to reproduce:]

1. open an idris file
2. ALT-CTL-r

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: linux 4.9.53
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.4.10

### Stack Trace

Uncaught At 0 expected: ( found: f

```
At /home/stewart/.atom/packages/language-idris/node_modules/bennu/dist_node/parse.js:756

At undefined undefined
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:141:25)
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:858:3)
    at Module.get_Module._compile (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/node_modules/bennu/index.js:2:14)
    at /packages/language-idris/node_modules/bennu/index.js:7:3)
    at Module.get_Module._compile (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/parse.coffee:1:25)
    at /packages/language-idris/lib/parse.coffee:1:1)
    at /packages/language-idris/lib/parse.coffee:1:1)
    at Module.get_Module._compile (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
    at Module.get_Module._compile (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/nix/store/isfkvvd032s5kwikrgqv9a5rxp6ixzq4-atom-beta-1.22.0-beta1/share/atom-beta/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

### Commands

```
  2x -4:25.3.0 core:copy (div.package-detail.panels-item)
     -2:55.5.0 core:select-all (input.hidden-input)
     -2:55.2.0 core:copy (input.hidden-input)
     -2:07.2.0 language-idris:typecheck (input.hidden-input)
     -1:58.5.0 core:backspace (input.hidden-input)
  3x -1:58 language-idris:typecheck (input.hidden-input)
     -1:39.4.0 core:backspace (input.hidden-input)
     -1:38.7.0 language-idris:typecheck (input.hidden-input)
     -1:33.2.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
editorconfig 2.2.2 
fonts 1.2.0 
ide-purescript 0.15.0 
language-capnproto 0.3.0 
language-elm 1.5.0 
language-haskell 1.12.1 
language-idris 0.4.10 
language-latex 1.0.0 
language-purescript 0.8.2 
language-rust 0.4.6 
language-tcl 0.1.2 
linter 1.11.4 
linter-rust 0.4.6 
nix 2.1.0 
racer 0.20.0 
split-diff 1.5.1 
```

**Comment by pjgoodall** [comment]
Always happens to me. For about a year now.No progress. Is there an equivalent to the 'this bug effects me' vote?

**Comment by justjoheinz** [comment]
@pjgoodall You could create a gist or some other file sharing thingie with a reproducible project. That would make it easier for me to look into this..
