### ISSUE TITLE
Idris compiler crash

### ISSUE THREAD

**Issue by machunter** [idris-hackers/atom-language-idris#221]
After updating both the Idris compiler to the latest Mac distribution and the Atom plugin, I can use the interactive feature of the plugin.

The first time I use one of the feature (say type check), I get the following error:
`The idris compiler was closed or crashed
It (probably) crashed with the error code: 1`

Subsequent attempt to use any of the interactive features I get the same error as reported in #192 but with a different stack trace:

`TypeError: Cannot read property 'length' of undefined
    at IdrisController.displayErrors (/Users/burcsahinoglu/.atom/packages/language-idris/lib/idris-controller.coffee:577:5)
    at AnonymousObserver._onError (/Users/burcsahinoglu/.atom/packages/language-idris/lib/idris-controller.coffee:1:1)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1643:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at AnonymousObserver.tryCatcher (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.error (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:4667:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1872:48)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at loopRecursive (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2412:18)
    at Rx.internals.ScheduledItem.invokeRecImmediate [as action] (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:929:7)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at FilterObservable.Rx.ObservableBase.ObservableBase._subscribe (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/burcsahinoglu/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)`

**Comment by machunter** [comment]
I added an executable script called myidris under `/usr/local/bin` with the following line `/usr/local/bin/idris $@`, referenced it in the plugin and everything started working again.

I'm going to assume that something is missing in my environment, but what?

**Comment by justjoheinz** [comment]
Very hard to help you here. Did you install idris via brew? This works flawlessly for me when I set the idris path to `/usr/local/bin/idris`.
Did you compare the file permissions? Is there any difference there?
