### ISSUE TITLE
When re-calling 'do case split' – Uncaught At 0 expected: ( found: :

### ISSUE THREAD

**Issue by CodingCellist** [idris-hackers/atom-language-idris#227]
This somehow happens on a file of mine. I don't know if it is because of the size or something, the file is only just over 500 lines with coments.

1. Try to case-split using the plugin. This hangs forever.
2. Re-call/Re-fresh the case-split command by pressing `Ctrl`+`Alt`+`c`. This results in the first case split appearing correctly, but also throws the error in the stack trace.

**Atom**: 1.34.0 x64
**Electron**: 3.1.1
**OS**: linux 4.20.4-arch1-1-ARCH
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.5.0

### Stack Trace

Uncaught At 0 expected: ( found: :

```
At ~/.atom/packages/language-idris/node_modules/bennu/dist_node/parse.js:756

At undefined undefined
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:141:25)
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:858:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/language-idris/node_modules/bennu/index.js:2:14)
    at /packages/language-idris/node_modules/bennu/index.js:7:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/language-idris/lib/utils/parse.coffee:1:25)
    at /packages/language-idris/lib/utils/parse.coffee:1:1)
    at /packages/language-idris/lib/utils/parse.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
```

### Commands

```
     -1:50.9.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:50.9.0 autocomplete-plus:confirm (input.hidden-input)
     -1:46.8.0 autocomplete-plus:cancel (input.hidden-input)
  3x -1:45.8.0 core:move-left (input.hidden-input)
     -1:44.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:44.1.0 markdown-writer:insert-new-line (input.hidden-input)
     -1:44.1.0 editor:newline (input.hidden-input)
     -1:37.5.0 core:move-right (input.hidden-input)
  6x -1:33.3.0 core:backspace (input.hidden-input)
     -1:29.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -1:24.4.0 markdown-writer:indent-list-line (input.hidden-input)
     -1:24.4.0 autocomplete-plus:confirm (input.hidden-input)
     -0:59.5.0 core:move-right (input.hidden-input)
     -0:59 core:save (input.hidden-input)
     -0:55.6.0 language-idris:add-clause (input.hidden-input)
  4x -0:47.9.0 language-idris:case-split (input.hidden-input)
```

### Non-Core Packages

```
language-haskell 1.18.0 
language-idris 0.5.0 
markdown-writer 2.11.3 
```

**Comment by justjoheinz** [comment]
Without a file or gist of the file I am unable to diagnose the issue. Can you provide a minimal testcase?
