### ISSUE TITLE
Cannot load package 'idris-ct' from .ipkg file

### ISSUE THREAD

**Issue by nasosev** [idris-hackers/atom-language-idris#242]
I cannot load the `idris-ct` package (https://github.com/statebox/idris-ct) in Atom using an .ipkg file following the instructions https://idris.readthedocs.io/en/latest/tutorial/packages.html#package-dependencies-using-atom

Note that:
i. I can load the package `pruviloj` without problems in Atom.
ii. I can load `idris-ct` without problems in the terminal using command `idris -p idris-ct`

[Enter steps to reproduce:]

1. Install idris-ct with command `idris --install idris-ct.ipkg`
2. make new directory myProject with file myProject.ipkg containing 

```
package myProject
pkgs = idris-ct
```
3. make new file myProject.idr, open directory with atom using command `atom .` and press Ctrl+Alt+R to typecheck
4. error : 
```
The idris compiler was closed or crashed
It (probably) crashed with the error code: 1:
```
5. Ctrl+Alt+R again yields the error below.

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Ubuntu 19.10
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.5.1

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/n0v4/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:78

TypeError: Cannot read property 'length' of undefined
    at IdrisController.displayErrors (/packages/language-idris/lib/idris-controller.coffee:580:5)
    at AnonymousObserver._onError (/packages/language-idris/lib/idris-controller.coffee:1:1)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1643:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at AnonymousObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:4667:14)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at MergeAllObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:3237:16)
    at MergeAllObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.error (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6268:52)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1579:14)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1872:48)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at InnerObserver.tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at AutoDetachObserverPrototype.next (/packages/language-idris/node_modules/rx-lite/rx.lite.js:6260:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1569:31)
    at loopRecursive (/packages/language-idris/node_modules/rx-lite/rx.lite.js:2412:18)
    at /packages/language-idris/node_modules/rx-lite/rx.lite.js:929:7)
    at Rx.internals.ScheduledItem.ScheduledItem.invokeCore (/packages/language-idris/node_modules/rx-lite/rx.lite.js:858:33)
    at Rx.internals.ScheduledItem.ScheduledItem.invoke (/packages/language-idris/node_modules/rx-lite/rx.lite.js:846:40)
    at runTrampoline (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1045:37)
    at tryCatcher (/packages/language-idris/node_modules/rx-lite/rx.lite.js:64:31)
    at CurrentThreadScheduler.schedule (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1061:45)
    at FilterObservable.Rx.ObservableBase.ObservableBase._subscribe (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1826:32)
    at FilterObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/packages/language-idris/node_modules/rx-lite/rx.lite.js:1703:19)
```

### Commands

```
  2x -0:14.4.0 language-idris:typecheck (input.hidden-input)
```

### Non-Core Packages

```
language-idris 0.5.1 
```

**Comment by nasosev** [comment]
I just discovered that a workaround is to put `opts = "-p idris-ct"` in the .ipkg file instead of `pkgs = idris-ct`.

**Comment by justjoheinz** [comment]
Sorry, that it took so long to get back to you. Thanks to your description I figured out that Atom currently does not allow "-", "_" to be part of the package name, when using the pkgs field. Will hopefully fix this soon.
