### ISSUE TITLE
Uncaught At 0 expected: ( found: h

### ISSUE THREAD

**Issue by vfrinken** [idris-hackers/atom-language-idris#249]
probably similar to #193

[Enter steps to reproduce:]

basically the moment I start writing idris code, I'm using Idris2 0.2.0 as idris executable

1. create a new file, write code, compile (Ctrl+r) and after that, with every character I write, this error box appears

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.14.6
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package 0.6.0

### Stack Trace

Uncaught At 0 expected: ( found: h

```
At /Users/frinken/.atom/packages/language-idris/node_modules/bennu/dist_node/parse.js:756

At undefined undefined
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:141:25)
    at /packages/language-idris/node_modules/bennu/dist_node/parse.js:858:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/language-idris/node_modules/bennu/index.js:2:14)
    at /packages/language-idris/node_modules/bennu/index.js:7:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/language-idris/lib/utils/parse.coffee:1:25)
    at /packages/language-idris/lib/utils/parse.coffee:1:1)
    at /packages/language-idris/lib/utils/parse.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147450)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150998)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146766)
    at /packages/language-idris/lib/idris-ide-mode.coffee:3:9)
    at /packages/language-idris/lib/idris-ide-mode.coffee:1:1)
```

### Commands

```
  7x -0:10.3.0 core:backspace (input.hidden-input)
     -0:08.8.0 editor:newline (input.hidden-input)
  2x -0:08.0 language-idris:typecheck (input.hidden-input)
  3x -0:02.4.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 2.0.1 
define-jump 1.0.1 
file-type-icons 1.3.4 
git-plus 8.7.1 
haskell-ghc-mod 2.2.6 
highlight-selected 0.17.0 
ide-haskell 2.4.1 
ide-haskell-cabal 2.5.0 
intentions 1.1.5 
language-cmake 1.2.0 
language-cuda 0.1.0 
language-haskell 1.19.4 
language-idris 0.6.0 
language-latex 1.2.0 
language-lua 0.9.11 
language-matlab 0.2.1 
language-protobuf 0.7.1 
latex 0.50.2 
latexer 0.3.0 
linter 2.3.1 
linter-clang 4.1.2 
linter-cpplint 2.1.0 
linter-ui-default 1.8.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
pdf-view 0.72.0 
piatto-light 2.0.2 
remote-atom 1.3.12 
split-diff 1.6.1 
symbols-tree-view 0.14.0 
teletype 0.13.4 
terminal-plus 0.14.5 
wordcount 3.2.0 
```

**Comment by justjoheinz** [comment]
idris 2 is currently not supported.
see #219 which also does not track the latest developments. I particularily never tested whether the IDE protocol changed a lot with 0.2.0 which would explain the error stack trace.
