### ISSUE TITLE
Uncaught Error: Notification must be created with string message: undefined

### ISSUE THREAD

**Issue by NightRa** [idris-hackers/atom-language-idris#45]
After the latest update - 0.2.1, this error occurs when I execute typechecking.

**Atom Version**: 1.0.5
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.1

### Stack Trace

Uncaught Error: Notification must be created with string message: undefined

```
At D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\notification.js:25

Error: Notification must be created with string message: undefined
    at Notification.module.exports.Notification.validate (D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\notification.js:25:15)
    at new Notification (D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\notification.js:20:12)
    at NotificationManager.module.exports.NotificationManager.addError (D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\notification-manager.js:41:35)
    at IdrisIdeMode.stopped (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-ide-mode.coffee:64:26)
    at ChildProcess.<anonymous> (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-ide-mode.coffee:3:61)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands

```
     -0:05.7.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -0:05.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 language-idris:typecheck (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "language-idris": {}
}
```

### Installed Packages

```coffee
# User
atom-terminal-panel, v4.4.4
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.8
ide-haskell, v0.7.1
language-haskell, v1.3.0
language-idris, v0.2.1
language-scala, v1.1.3

# Dev
No dev packages
```

**Comment by archaeron** [comment]
damn, that's not really a better error message. Thanks for reporting this. is it the only message oyu get?

**Comment by NightRa** [comment]
Later I get this:
### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:141

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:275:12)
    at IdrisIdeMode.send (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-ide-mode.coffee:41:33)
    at IdrisModel.prepareCommand (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-model.coffee:88:22)
    at IdrisModel.load (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-model.coffee:93:19)
    at IdrisController.doCaseSplit (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-controller.coffee:166:25)
    at D:\Users\NightRa\.atom\packages\language-idris\lib\idris-controller.coffee:3:61
    at atom-text-editor.<anonymous> (D:\Users\NightRa\.atom\packages\language-idris\lib\idris-controller.coffee:79:18)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:241:29)
    at D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Users\NightRa\AppData\Local\atom\app-1.0.5\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
```

**Comment by archaeron** [comment]
I made a stupid mistake before.
could you check if you get at least more helpful error messages now? :)

**Comment by NightRa** [comment]
```It (probably) crashed with the error code: 1```

**Comment by archaeron** [comment]
If I wrote the error handling correctly this means that Idris crashed after starting it.

Does the compiler work for you from the commandline?
Did you put the path to the compiler in the settings?

**Comment by NightRa** [comment]
Yes it does work.
This happens (it crashes) if the first command I do is "Typecheck".
If I do some other command first, like case splitting, then I can typecheck
and nothing crashes.
Also, idris doesn't seem to recognize anything (for type-of and others)
until I do a typecheck.

2015-08-09 17:46 GMT+03:00 archaeron <notifications@github.com>:

**Comment by archaeron** [comment]
And you're using the latest version? 0.9.18 or above?

The case splitting that you spone of. Does that one work? Does it really split?

Typechecking is needed for every other command as it loads the idris file into the compiler.

**Comment by NightRa** [comment]
Yes, I'm on the latest 0.9.18 version.
It should typecheck automatically before every command then.

Now I can't reproduce the error anymore. Beforehand I couldn't do any
command at all and now it all works fine again.

2015-08-09 17:52 GMT+03:00 archaeron <notifications@github.com>:

**Comment by archaeron** [comment]
It typechecks automatically for you before every command that changes your file, like case splitting.
It doesn't at the moment for commands like getting the type of a word.

Can I close the issue?

**Comment by NightRa** [comment]
For now, yes.
If the issue comes back I'll open a new ticket. (or ask to reopen this one)

2015-08-09 18:15 GMT+03:00 archaeron <notifications@github.com>:

**Comment by archaeron** [comment]
sounds fair :) thanks.
