### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdin' of null

### ISSUE THREAD

**Issue by jeremy-w** [idris-hackers/atom-language-idris#46]
1. Install the package
2. Create a new buffer
3. Try to get docs with Ctrl-Opt-d or via the command palette

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At /Users/jeremy/.atom/packages/language-idris/lib/idris-ide-mode.coffee:24

TypeError: Cannot read property 'stdin' of null
  at IdrisIdeMode.send (/Users/jeremy/.atom/packages/language-idris/lib/idris-ide-mode.coffee:24:13)
  at IdrisModel.prepareCommand (/Users/jeremy/.atom/packages/language-idris/lib/idris-model.coffee:58:16)
  at IdrisModel.docsFor (/Users/jeremy/.atom/packages/language-idris/lib/idris-model.coffee:65:6)
  at IdrisController.getDocsForWord (/Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:79:8)
  at /Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
  at atom-text-editor.<anonymous> (/Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:48:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:36.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  7x -2:32.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -2:27.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  7x -2:25.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  9x -2:22.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  3x -2:20.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  3x -2:19.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -2:17.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:17.4.0 language-idris:docs-for (atom-text-editor.editor)
     -1:51.7.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:26.8.0 core:confirm (atom-text-editor#language-idris.pathToIdris.editor.mini.is-focused)
     -0:35.4.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -0:34.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:20.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:14 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:14 language-idris:docs-for (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "language-idris": {
    "pathToIdris": "/usr/local/bin/idris"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.8
ide-haskell, v0.7.1
language-haskell, v1.3.0
language-idris, v0.2.1

# Dev
No dev packages
```

**Comment by archaeron** [comment]
is this a new error or did it only occur since the new version?

**Comment by jeremy-w** [comment]
I only just installed Atom today, so I can't tell if it's a regression, sorry. :(
--
Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by archaeron** [comment]
no problem :)

**Comment by archaeron** [comment]
@jeremy-w could you check this again?
It probably still won't work if the process crashes, but I'm hoping that the new error messages help in finding the culprit.

**Comment by jeremy-w** [comment]
I tried it on a different machine, and getting docs worked there, even in an unsaved file, with v0.2.3.

**Comment by archaeron** [comment]
and on the same machine? :)

**Comment by jeremy-w** [comment]
Just tested there! It's working there as well. Seems fixed to me!

**Comment by archaeron** [comment]
awesome! and thank you :)
