### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by jeremy-w** [idris-hackers/atom-language-idris#47]
1. Create a new buffer.
2. Set its grammar to idris-language.
3. Invoke the typecheck command, as suggested in https://github.com/idris-hackers/atom-language-idris/blob/master/documentation/tutorial.md.

A few fixes come to mind:

- Disable that command for unsaved buffers (not sure atom lets you do this)
- Present a dialog to the user to tell them "save first"
- Save to a temp file and typecheck that (the save becomes transparent to the user, and the buffer is still not tied to a file on disk)

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.1

### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:998:15)
  at TextBuffer.module.exports.TextBuffer.save (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:992:19)
  at TextEditor.module.exports.TextEditor.save (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
  at IdrisController.typecheckFile (/Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:53:18)
  at /Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
  at atom-text-editor.<anonymous> (/Users/jeremy/.atom/packages/language-idris/lib/idris-controller.coffee:48:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/1.0.5/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:23.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:19.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:19.8.0 language-idris:typecheck (atom-text-editor.editor)
     -0:11.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 language-idris:typecheck (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "language-idris": {
    "pathToIdris": "/usr/local/bin/idris"
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.1
atom-material-ui, v0.5.13
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.8
ide-haskell, v0.7.1
language-haskell, v1.3.0
language-idris, v0.2.1

# Dev
No dev packages
```

**Comment by archaeron** [comment]
Hello
thanks for reporting this.
I think of your options I like the second one best.

I don't think number 1 (Disable that command for unsaved buffers) is possible as you said and on top of that it doesn't really help you. You'd just have an option that you can't use, without knowing why.

Number 3 could be unclear, for the user and would be pretty time expensive to implement, I don't think it's worth the hassle.

Number 2 tells you: hey something is not right, but here is how to fix it.

**Comment by david-christiansen** [comment]
What about just invoking the "Save as...." dialog if there's no filename?

**Comment by archaeron** [comment]
That would be even better :) Should be doable

**Comment by archaeron** [comment]
it opens the "Save as..." dialog now

**Comment by jeremy-w** [comment]
:+1: Just noticed this working. Is it possible to inject some explanatory text into the save-as dialog, like, "To typecheck, first save the file to disk:"?

**Comment by jeremy-w** [comment]
Poked at API. Looks like the answer is "no" - you'd have to do some intermediate dialog instead, which, yuck.

**Comment by archaeron** [comment]
:)
too much work to get right
