### ISSUE TITLE
Uncaught ReferenceError: editor is not defined

### ISSUE THREAD

**Issue by hannes-landeholm** [idris-hackers/atom-language-idris#49]
Reproduce:
1. Attempting to use "Showing the types of meta-variables (ctrl-alt-t)" on any position

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.3

### Stack Trace

Uncaught ReferenceError: editor is not defined

```
At /Users/hannes/.atom/packages/language-idris/lib/idris-controller.coffee:95

ReferenceError: editor is not defined
  at IdrisController.getTypeForWord (/Users/hannes/.atom/packages/language-idris/lib/idris-controller.coffee:95:11)
  at /Users/hannes/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
  at atom-text-editor.<anonymous> (/Users/hannes/.atom/packages/language-idris/lib/idris-controller.coffee:51:9)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:58.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:56.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:38.3.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.is-focused)
     -0:36.7.0 editor:select-line (atom-text-editor.editor.is-focused)
     -0:35.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:34.6.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:34.6.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:32.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:31.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:31.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:30.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:27.9.0 core:save (atom-text-editor.editor.is-focused)
  6x -0:05.5.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:04.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:00.9.0 language-idris:type-of (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "language-idris": {
    "pathToIdris": "/Users/hannes/Library/Haskell/bin/idris"
  }
}
```

### Installed Packages

```coffee
# User
language-idris, v0.2.3

# Dev
No dev packages
```

**Comment by archaeron** [comment]
well this is embarassing. Thanks for the report :)
