### ISSUE TITLE
Failed to activate the language-idris package

### ISSUE THREAD

**Issue by laughedelic** [idris-hackers/atom-language-idris#5]
Hi! I get an error when trying to install this plugin. I guess, it's just because of the atom API changes, but don't know how to fix it.

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.3
**Thrown From**: [language-idris](https://github.com/fangel/atom-language-idris) package, v0.0.1

### Stack Trace

Failed to activate the language-idris package

```
At undefined is not a function

TypeError: undefined is not a function
  at IdrisController.init (/Users/laughedelic/.atom/packages/language-idris/lib/idris-controller.js:57:20)
  at new IdrisController (/Users/laughedelic/.atom/packages/language-idris/lib/idris-controller.js:10:8)
  at Object.module.exports.activate (/Users/laughedelic/.atom/packages/language-idris/lib/language-idris.js:13:23)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
     -0:27.9 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode)
     -0:24.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:24.2 core:cancel (atom-text-editor.editor.mini)
     -0:23.6 settings-view:open (atom-text-editor.editor.vim-mode.command-mode)
     -0:19.2 core:confirm (atom-text-editor.editor.mini)
```

**Comment by laughedelic** [comment]
Oops! Sorry I just noticed that it's a duplicate of the #4.
But anyway, is this plugin still maintained?

**Comment by archaeron** [comment]
hello
I just pushed a new version to atom.io
could you test if it's working for you?
It is mantained again now

**Comment by Heather** [comment]
I will close it for now, please reopen if it will happen again
