### ISSUE TITLE
Most commands throw exceptions on Windows 8.1

### ISSUE THREAD

**Issue by aochagavia** [idris-hackers/atom-language-idris#69]
There are two kind of exceptions:

# Raised when using language-idris:docs-for

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'stdin' of null

```
At C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:549

TypeError: Cannot read property 'stdin' of null
  at IdrisIdeMode.send (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-ide-mode.coffee:51:13)
  at IdrisModel.prepareCommand (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:73:32)
  at IdrisModel.docsFor (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:98:6)
  at IdrisController.getDocsForWord (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:105:8)
  at C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:1:1
  at AnonymousObserver._onNext (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:63:11)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1811:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at AnonymousObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at InnerObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3092:90)
  at InnerObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at scheduleItem (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2566:16)
  at Scheduler.scheduleNow [as _schedule] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1173:50)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:957:19)
  at JustSink.run (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2571:36)
  at JustObservable.subscribeCore (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2556:19)
  at JustObservable.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at [object Object].setDisposable [as action] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1984:46)
  at [object Object].ScheduledItem.invokeCore (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:916:17)
  at [object Object].ScheduledItem.invoke (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:904:40)
  at runTrampoline (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1186:37)
  at tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at Scheduler.scheduleNow [as _schedule] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1197:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:957:19)
  at JustObservable.subscribe [as _subscribe] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1996:32)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1873:19)
  at MergeAllObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3060:37)
  at MergeAllObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at MapObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3862:19)
  at MapObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5631:17)
  at AsyncSubject.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1763:14)
  at AutoDetachObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1763:14)
  at handler (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:4223:20)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
  2x -2:36.6.0 language-idris:docs-for (atom-text-editor.editor.is-focused)
     -1:51.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:51.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:50.4.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -1:49.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:49.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:45.1.0 language-idris:case-split (atom-text-editor.editor.is-focused)
     -1:43.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:43.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:38.9.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -1:37.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:37.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:17.6.0 language-idris:proof-search (atom-text-editor.editor.is-focused)
     -1:09.5.0 language-idris:make-with (atom-text-editor.editor.is-focused)
     -1:03.8.0 language-idris:make-lemma (atom-text-editor.editor.is-focused)
     -0:03.6.0 language-idris:docs-for (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "language-idris": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.5.1
autocomplete-python, v0.5.4
build, v0.47.0
haskell-ghc-mod, v0.9.12
ide-haskell, v0.7.2
language-haskell, v1.4.9
language-idris, v0.3.2
language-rust, v0.4.5
racer, v0.17.2

# Dev
No dev packages
```

# Raised when using language-idris:typecheck (and other commands)

**Atom Version**: 1.0.19
**System**: Microsoft Windows 8.1
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.3.2

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:549

TypeError: Cannot read property 'length' of undefined
  at IdrisIdeMode.start (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-ide-mode.coffee:18:32)
  at IdrisModel.ideMode (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:19:19)
  at IdrisModel.prepareCommand (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:73:6)
  at IdrisModel.interpret (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:113:6)
  at IdrisModel.changeDirectory (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:77:6)
  at IdrisModel.load (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-model.coffee:89:10)
  at IdrisController.doMakeLemma (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:241:8)
  at C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:1:1
  at AnonymousObserver._onNext (C:\Users\Adolfo\.atom\packages\language-idris\lib\idris-controller.coffee:63:11)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1811:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at AnonymousObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at InnerObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3092:90)
  at InnerObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at scheduleItem (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2566:16)
  at Scheduler.scheduleNow [as _schedule] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1173:50)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:957:19)
  at JustSink.run (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2571:36)
  at JustObservable.subscribeCore (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:2556:19)
  at JustObservable.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at [object Object].setDisposable [as action] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1984:46)
  at [object Object].ScheduledItem.invokeCore (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:916:17)
  at [object Object].ScheduledItem.invoke (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:904:40)
  at runTrampoline (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1186:37)
  at tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at Scheduler.scheduleNow [as _schedule] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1197:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:957:19)
  at JustObservable.subscribe [as _subscribe] (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1996:32)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1873:19)
  at MergeAllObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3060:37)
  at MergeAllObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at MapObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3862:19)
  at MapObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1743:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5631:17)
  at AsyncSubject.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1763:14)
  at AutoDetachObserver.tryCatcher (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1763:14)
  at handler (C:\Users\Adolfo\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:4223:20)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -3:17.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -1:36.4.0 language-idris:docs-for (atom-text-editor.editor.is-focused)
     -0:51.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:50.2.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -0:49.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:49.6.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:44.9.0 language-idris:case-split (atom-text-editor.editor.is-focused)
     -0:43 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:43 core:cancel (atom-text-editor.editor.is-focused)
     -0:38.7.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -0:37 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:37 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:17.4.0 language-idris:proof-search (atom-text-editor.editor.is-focused)
     -0:09.3.0 language-idris:make-with (atom-text-editor.editor.is-focused)
     -0:03.6.0 language-idris:make-lemma (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "language-idris": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.5.1
autocomplete-python, v0.5.4
build, v0.47.0
haskell-ghc-mod, v0.9.12
ide-haskell, v0.7.2
language-haskell, v1.4.9
language-idris, v0.3.2
language-rust, v0.4.5
racer, v0.17.2

# Dev
No dev packages
```

**Comment by archaeron** [comment]
ah, I'm sorry for this. you're totally right. I should add tests for stuff like this. But I hate writing them :D
thanks for the fix.

**Comment by archaeron** [comment]
Or use a type system. That would help too
