### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by sgraf812** [idris-hackers/atom-language-idris#71]
1. Any Idris command (Typechecking in this case)

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.3.3

### Stack Trace

Uncaught Error: spawn EACCES

```
At /Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:549

Error: spawn EACCES
  at exports._errnoException (util.js:814:11)
  at ChildProcess.spawn (internal/child_process.js:298:11)
  at exports.spawn (child_process.js:343:9)
  at IdrisIdeMode.start (/Users/sgraf/.atom/packages/language-idris/lib/idris-ide-mode.coffee:38:9)
  at IdrisModel.ideMode (/Users/sgraf/.atom/packages/language-idris/lib/idris-model.coffee:19:19)
  at IdrisModel.prepareCommand (/Users/sgraf/.atom/packages/language-idris/lib/idris-model.coffee:73:6)
  at IdrisModel.interpret (/Users/sgraf/.atom/packages/language-idris/lib/idris-model.coffee:113:6)
  at IdrisModel.changeDirectory (/Users/sgraf/.atom/packages/language-idris/lib/idris-model.coffee:77:6)
  at IdrisModel.load (/Users/sgraf/.atom/packages/language-idris/lib/idris-model.coffee:89:10)
  at IdrisController.typecheckFile (/Users/sgraf/.atom/packages/language-idris/lib/idris-controller.coffee:86:8)
  at /Users/sgraf/.atom/packages/language-idris/lib/idris-controller.coffee:1:1
  at AnonymousObserver._onNext (/Users/sgraf/.atom/packages/language-idris/lib/idris-controller.coffee:63:11)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1811:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1743:35)
  at AnonymousObserver.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1743:35)
  at InnerObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3092:90)
  at InnerObserver.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1743:35)
  at scheduleItem (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2566:16)
  at Scheduler.scheduleNow [as _schedule] (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1173:50)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:957:19)
  at JustSink.run (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2571:36)
  at JustObservable.subscribeCore (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:2556:19)
  at JustObservable.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at [object Object].setDisposable [as action] (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1984:46)
  at [object Object].ScheduledItem.invokeCore (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:916:17)
  at [object Object].ScheduledItem.invoke (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:904:40)
  at runTrampoline (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1186:37)
  at tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at Scheduler.scheduleNow [as _schedule] (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1197:45)
  at Scheduler.Rx.Scheduler.schedulerProto.scheduleWithState (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:957:19)
  at JustObservable.subscribe [as _subscribe] (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1996:32)
  at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1873:19)
  at MergeAllObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3060:37)
  at MergeAllObserver.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1743:35)
  at MapObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:3862:19)
  at MapObserver.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.next (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5421:51)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1743:35)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onCompleted (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5631:17)
  at AsyncSubject.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1763:14)
  at AutoDetachObserver.tryCatcher (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:537:29)
  at AutoDetachObserverPrototype.completed (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:5435:56)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:1763:14)
  at handler (/Users/sgraf/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:4223:20)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
  7x -3:15.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -3:13.7.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -3:13.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
 13x -3:12.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  9x -3:10.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -3:09.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:08.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:07.5.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:06.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 12x -3:05.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:03.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -3:02.4.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -3:01.7.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:58.9.0 pane:show-next-item (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -2:57.4.0 pane:show-previous-item (div.settings-view.pane-item)
  2x -2:56.3.0 language-idris:typecheck (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {},
  "language-idris": {
    "pathToIdris": "/Users/sgraf/.cabal/bin"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-haskell, v0.5.1
haskell-ghc-mod, v0.9.12
language-elm, v1.0.3
language-haskell, v1.4.9
language-idris, v0.3.3
minimap, v4.13.4
sync-settings, v0.6.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by archaeron** [comment]
hello and sorry for the delay

do you have access rights to your idris command?
try running it manually from the command line. if you've set the path to the compiler in the settings use that one, if not use the one from your PATH variable.

just try:
```sh
> idris
```

this is how it looks for me:

![idris_repl](https://cloud.githubusercontent.com/assets/471043/10365968/7b33dc80-6dc7-11e5-9a24-3bbe33fb88a9.PNG)

**Comment by sgraf812** [comment]
Hi,

this is my output:

```
Can't find import Builtins
Can't find import Prelude
     ____    __     _                                          
    /  _/___/ /____(_)____                                     
    / // __  / ___/ / ___/     Version 0.9.19.1
  _/ // /_/ / /  / (__  )      http://www.idris-lang.org/      
 /___/\__,_/_/  /_/____/       Type :? for help               

Idris is free software with ABSOLUTELY NO WARRANTY.            
For details type :warranty.
Idris> 
```

I just noticed that idris can't find the builtins nor the prelude, so that's probably it.

I guess just copying over the executables from a cabal sandbox isn't enough.

**Comment by archaeron** [comment]
Is that the same idris the package uses? Could you check in the settings, just to be safe?

you could add the path to you cabal sanbox bin directory to your PATH instead of copying the executable.

**Comment by sgraf812** [comment]
I'm pretty sure that's the executable atom should find too, given that atom points to the same path as returned by `which`.

Adding the sandbox to the path would probably fix it (I'll try that out), but I'd rather like to make it work without changing my path.

**Comment by archaeron** [comment]
ah, I overlooked the config hash. sorry for that.

as soon as you manage to fix the two warnings, could you tell me if that fixed it for you?
because everything seems fine other than that

**Comment by sgraf812** [comment]
So I rebuilt idris again in a sandbox and made language-idris point to that sandbox. I launched the idris REPL from within the sandbox, the warning about the Prelude and Builtins were gone. However, I still get the same error when trying `ctrl+alt+t` on any expression.

**Comment by archaeron** [comment]
I would test this out, if cabal would still work after the update. :(

**Comment by archaeron** [comment]
Got it to work. `idris-0.9.19.1` in a sandbox.

`ctrl+alt+t` is working fine.

How do you start atom?

**Comment by sgraf812** [comment]
I installed atom via homebrew, so that the path variable is properly inherited (at least I think that's the case). I start atom mostly from spotlight.

**Comment by archaeron** [comment]
what user owns the idris executable?

**Comment by sgraf812** [comment]
```
$ pwd
/Users/sgraf/Documents/code/haskell/idris/.cabal-sandbox/bin
$ la
total 396352
-rwxr-xr-x  1 sgraf  staff    12M  9 Okt 10:25 cheapskate
-rwxr-xr-x  1 sgraf  staff    46M  9 Okt 10:36 idris
-rwxr-xr-x  1 sgraf  staff    44M  9 Okt 10:36 idris-codegen-c
-rwxr-xr-x  1 sgraf  staff    45M  9 Okt 10:36 idris-codegen-javascript
-rwxr-xr-x  1 sgraf  staff    45M  9 Okt 10:36 idris-codegen-node
```

So that seems OK.

**Comment by archaeron** [comment]
oh, wait. Could you do me a favour and replace the path `/Users/sgraf/.cabal/bin` with `/Users/sgraf/.cabal/bin/idris` and try again?

**Comment by sgraf812** [comment]
Great, it works :) and shame on me for not trying the obvious.

**Comment by archaeron** [comment]
sorry, I should have caught this earlier :(

closing this issue and glad it's working now :)

**Comment by archaeron** [comment]
Ps: there is a description in the settings

![path_to_idris](https://cloud.githubusercontent.com/assets/471043/10558806/02ab6134-74de-11e5-806c-a6b5603abe5b.PNG)


But it would be best to check if the thing the settings points to is an executable or a folder.

**Comment by david-christiansen** [comment]
What about changing the header to "Idris Location" and the description to "Location of the Idris executable" or "How to invoke Idris compiler"? That would make it more clear what's needed here, I think.

**Comment by archaeron** [comment]
:+1: good suggestion, thanks
