### ISSUE TITLE
Failed to load the language-idris package

### ISSUE THREAD

**Issue by melaanya** [idris-hackers/atom-language-idris#81]
[Enter steps to reproduce below:]

1. Every time I open atom I get this message => can't use this package

**Atom Version**: 1.1.0-beta1
**System**: Windows 7 64-bit
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.3.3

### Stack Trace

Failed to load the language-idris package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Анна\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Анна\.atom\packages\language-idris\lib\idris-controller.coffee:2:3)
    at Object.<anonymous> (C:\Users\Анна\.atom\packages\language-idris\lib\idris-controller.coffee:1:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Анна\AppData\Local\atom\app-1.1.0-beta1\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-idris, v0.3.3

# Dev
No dev packages
```

**Comment by archaeron** [comment]
How did you install the package? through the settings or by cloning it yourself?

**Comment by melaanya** [comment]
Through the settings

**Comment by archaeron** [comment]
Atom should install the dependencies when you install the package from the settings.
You are using a beta version, maybe something is broken?

There is a workaround. You can go the the folder of the package in the terminal and use `apm install`.
The folder is under: `{user-dir}/.atom/packages/language-idris`.

so:

```bash
{user-dir}/.atom/packages/language-idris
apm install
```

**Comment by melaanya** [comment]
I reinstalled Atom, now it's 1.0.19 - last released, then did the the actions you recommend and it was written that installation is done, but still get the same mistake wnen opening any file.

**Comment by archaeron** [comment]
I pushed an update. Is it still broken?

**Comment by melaanya** [comment]
I reinstalled the package, but yes, I'm still getting the same message. 
By the way, I noticed that those, who have Windows 10, don't have such a problem (even before the update).

**Comment by archaeron** [comment]
I only have Windows 10 computers at my disposal I'm sorry. Could you look in 
`{user-dir}/.atom/packages/language-idris/node_modules` if you have a folder called `atom-message-panel`?

If it doesn't work, try replacing `apm` in the command above with `npm`

```
{user-dir}/.atom/packages/language-idris
npm install
```

**Comment by melaanya** [comment]
Yes, there is a folder with such a name.

**Comment by archaeron** [comment]
It looks a bit like there is an error in Atom.
See here:
https://github.com/atom/atom/issues/8891

What if you remove the folder and reinstall it with `apm install`? Apparently there was an error with the npm servers sometime ago.

**Comment by archaeron** [comment]
Oh further down they say that most of them have cyrillic letters in their path. (Or another non-ascii letter). What about you?

**Comment by melaanya** [comment]
Yes, maybe it's a problem, because I do have cyrillic letters in the path! I don't see any possibility of changing the folder via installation, so I'll try to change the path itself and then report you.

**Comment by melaanya** [comment]
Now I've changed the name of my user directory and the previous error doesn't appear!
But I'm getting this one (when try to typecheck, for example):

Uncaught [object Object]
C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:756
Hide Stack Trace
At undefined undefined
    at Object.<anonymous> (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\bennu\dist_node\parse.js:141:25)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Anna.melaanya\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\bennu\index.js:2:14)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Anna.melaanya\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)

**Comment by archaeron** [comment]
Hey

sorry for the delay.

Did you test it with the newest version of atom? It came out just some days ago.

If the error is still there, could you explain to me the steps you took to get the error to appear?

**Comment by melaanya** [comment]
Yes, I downloaded the newset version, and the error is still the same. 

I open the .idr file, then try to typecheck using one of keybindings - ctrl + alt + r, then I get the error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.4.0


### Stack Trace

Uncaught Error: This socket is closed.

```
At C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:78

Error: This socket is closed.
  at Socket._writeGeneric (net.js:637:19)
  at Socket._write (net.js:691:8)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at Socket.Writable.write (_stream_writable.js:206:11)
  at Socket.write (net.js:615:40)
  at IdrisIdeMode.send (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-ide-mode.coffee:51:20)
  at IdrisModel.prepareCommand (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-model.coffee:74:32)
  at IdrisModel.interpret (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-model.coffee:114:6)
  at IdrisModel.changeDirectory (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-model.coffee:78:6)
  at IdrisModel.load (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-model.coffee:90:10)
  at IdrisController.typecheckFile (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-controller.coffee:89:8)
  at C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-controller.coffee:1:1
  at AnonymousObserver._onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\lib\idris-controller.coffee:69:11)
  at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1643:12)
  at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at AnonymousObserver.tryCatcher (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
  at AutoDetachObserverPrototype.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6268:52)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at MergeAllObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:3237:16)
  at MergeAllObserver.tryCatcher (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
  at AutoDetachObserverPrototype.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6268:52)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at InnerObserver.Rx.FlatMapObservable.InnerObserver.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1879:58)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at InnerObserver.tryCatcher (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
  at AutoDetachObserverPrototype.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6268:52)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at InnerObserver.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:4333:14)
  at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at InnerObserver.tryCatcher (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:64:31)
  at AutoDetachObserverPrototype.error (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6268:52)
  at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:1579:14)
  at AsyncSubject.Rx.AsyncSubject.addProperties.onError (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:6486:19)
  at handler (C:\Users\Anna.melaanya\.atom\packages\language-idris\node_modules\rx-lite\rx.lite.js:4749:25)
  at FSReqWrap.oncomplete (fs.js:82:15)

```

### Commands

```
     -2:07.4.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -1:20.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:16.1.0 window:run-package-specs (atom-text-editor.editor.is-focused)
  2x -1:14.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:00.5.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -0:53 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:47.5.0 core:paste (atom-text-editor#language-idris.pathToIdris.editor.mini.is-focused)
     -0:32.7.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "language-idris": {
    "pathToIdris": "D:\\study\\idris\\idris"
  }
}
```

### Installed Packages

```coffee
# User
language-idris, v0.4.0

# Dev
No dev packages
```
